apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume-claim
  namespace: imagecollector
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
